import type { ProductionSnapshot, SectorKey } from "./types";

const anchorDate = new Date("2026-03-16T14:20:00-03:00");

const buildDate = (hour: number, minute: number, dayOffset = 0) => {
  const date = new Date(anchorDate);
  date.setDate(date.getDate() + dayOffset);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
};

export const sectorSequence: SectorKey[] = [
  "corte",
  "costura",
  "acabamento",
  "expedicao",
];

export function createInitialProductionSnapshot(): ProductionSnapshot {
  return {
    tick: 0,
    scenarioKey: "turno_estavel",
    currentTime: anchorDate.toISOString(),
    shiftLabel: "A",
    connectedOperators: 38,
    productMix: 5,
    dailyTarget: 1500,
    dailyProduced: 1128,
    projectedCompletion: 92,
    defectRate: 1.86,
    downtimeMinutes: 37,
    products: [
      {
        id: "prod-01",
        name: "Camiseta basica",
        sku: "RM-100",
        category: "Malha",
        standardMinuteValue: 7.2,
        averageUnitsPerHour: 340,
      },
      {
        id: "prod-02",
        name: "Polo masculina",
        sku: "RM-215",
        category: "Malha premium",
        standardMinuteValue: 9.8,
        averageUnitsPerHour: 220,
      },
      {
        id: "prod-03",
        name: "Moletom feminino",
        sku: "RM-302",
        category: "Inverno",
        standardMinuteValue: 12.4,
        averageUnitsPerHour: 130,
      },
      {
        id: "prod-04",
        name: "Calca de uniforme",
        sku: "RM-411",
        category: "Uniformes",
        standardMinuteValue: 11.2,
        averageUnitsPerHour: 180,
      },
      {
        id: "prod-05",
        name: "Jaqueta leve",
        sku: "RM-518",
        category: "Outerwear",
        standardMinuteValue: 15.5,
        averageUnitsPerHour: 98,
      },
    ],
    operators: [
      {
        id: "op-01",
        name: "Ana Claudia",
        sector: "corte",
        shift: "A",
        efficiencyScore: 96,
        role: "Supervisora de corte",
        lineId: "line-corte-01",
        badge: "RM-4012",
        experienceYears: 9,
      },
      {
        id: "op-02",
        name: "Renato Alves",
        sector: "corte",
        shift: "A",
        efficiencyScore: 91,
        role: "Operador de enfesto",
        lineId: "line-corte-01",
        badge: "RM-4018",
        experienceYears: 6,
      },
      {
        id: "op-03",
        name: "Miriam Dantas",
        sector: "costura",
        shift: "A",
        efficiencyScore: 95,
        role: "Lider de linha",
        lineId: "line-costura-01",
        badge: "RM-5122",
        experienceYears: 11,
      },
      {
        id: "op-04",
        name: "Juliana Reis",
        sector: "costura",
        shift: "A",
        efficiencyScore: 87,
        role: "Operadora overlock",
        lineId: "line-costura-01",
        badge: "RM-5136",
        experienceYears: 4,
      },
      {
        id: "op-05",
        name: "Bruna Souza",
        sector: "costura",
        shift: "A",
        efficiencyScore: 89,
        role: "Operadora reta",
        lineId: "line-costura-02",
        badge: "RM-5141",
        experienceYears: 5,
      },
      {
        id: "op-06",
        name: "Carlos Neri",
        sector: "costura",
        shift: "A",
        efficiencyScore: 93,
        role: "Preparador de linha",
        lineId: "line-costura-02",
        badge: "RM-5148",
        experienceYears: 8,
      },
      {
        id: "op-07",
        name: "Ariane Lopes",
        sector: "acabamento",
        shift: "A",
        efficiencyScore: 94,
        role: "Lider de acabamento",
        lineId: "line-acab-01",
        badge: "RM-6210",
        experienceYears: 7,
      },
      {
        id: "op-08",
        name: "Marcos Teles",
        sector: "acabamento",
        shift: "A",
        efficiencyScore: 88,
        role: "Revisor final",
        lineId: "line-acab-01",
        badge: "RM-6216",
        experienceYears: 5,
      },
      {
        id: "op-09",
        name: "Helena Pires",
        sector: "acabamento",
        shift: "A",
        efficiencyScore: 92,
        role: "Inspetora de qualidade",
        lineId: "line-acab-01",
        badge: "RM-6222",
        experienceYears: 6,
      },
      {
        id: "op-10",
        name: "Igor Martins",
        sector: "expedicao",
        shift: "A",
        efficiencyScore: 86,
        role: "Separador de pedidos",
        lineId: "line-exp-01",
        badge: "RM-7301",
        experienceYears: 3,
      },
      {
        id: "op-11",
        name: "Fernanda Costa",
        sector: "expedicao",
        shift: "A",
        efficiencyScore: 90,
        role: "Conferente final",
        lineId: "line-exp-01",
        badge: "RM-7306",
        experienceYears: 7,
      },
      {
        id: "op-12",
        name: "Sergio Lima",
        sector: "expedicao",
        shift: "A",
        efficiencyScore: 84,
        role: "Analista de expedicao",
        lineId: "line-exp-01",
        badge: "RM-7311",
        experienceYears: 4,
      },
    ],
    lines: [
      {
        id: "line-corte-01",
        name: "Linha 07",
        sector: "corte",
        supervisorId: "op-01",
        operatorIds: ["op-01", "op-02"],
        targetPerHour: 150,
        taktTimeSeconds: 24,
        color: "#73a8f8",
      },
      {
        id: "line-costura-01",
        name: "Linha 01",
        sector: "costura",
        supervisorId: "op-03",
        operatorIds: ["op-03", "op-04"],
        targetPerHour: 205,
        taktTimeSeconds: 18,
        color: "#3ea6a6",
      },
      {
        id: "line-costura-02",
        name: "Linha 03",
        sector: "costura",
        supervisorId: "op-06",
        operatorIds: ["op-05", "op-06"],
        targetPerHour: 180,
        taktTimeSeconds: 20,
        color: "#efbc68",
      },
      {
        id: "line-acab-01",
        name: "Linha 05",
        sector: "acabamento",
        supervisorId: "op-07",
        operatorIds: ["op-07", "op-08", "op-09"],
        targetPerHour: 165,
        taktTimeSeconds: 22,
        color: "#86c56d",
      },
      {
        id: "line-exp-01",
        name: "Linha 02",
        sector: "expedicao",
        supervisorId: "op-11",
        operatorIds: ["op-10", "op-11", "op-12"],
        targetPerHour: 140,
        taktTimeSeconds: 26,
        color: "#eb7d76",
      },
    ],
    machines: [
      {
        id: "mc-01",
        code: "CRT-01",
        name: "Mesa automatica Lectra A1",
        sector: "corte",
        lineId: "line-corte-01",
        machineType: "Corte automatico",
        serialNumber: "RM-CRT-8841",
        nominalEfficiency: 95,
        runtimeTodayMinutes: 412,
        maintenanceWindow: "22/03 06:00",
      },
      {
        id: "mc-02",
        code: "CRT-02",
        name: "Enfestadeira Bullmer E2",
        sector: "corte",
        lineId: "line-corte-01",
        machineType: "Enfesto",
        serialNumber: "RM-CRT-8847",
        nominalEfficiency: 92,
        runtimeTodayMinutes: 388,
        maintenanceWindow: "25/03 18:00",
      },
      {
        id: "mc-03",
        code: "CST-11",
        name: "Reta eletronica Juki 11A",
        sector: "costura",
        lineId: "line-costura-01",
        machineType: "Costura reta",
        serialNumber: "RM-CST-1021",
        nominalEfficiency: 93,
        runtimeTodayMinutes: 421,
        maintenanceWindow: "19/03 07:30",
      },
      {
        id: "mc-04",
        code: "CST-12",
        name: "Overlock Pegasus 12B",
        sector: "costura",
        lineId: "line-costura-01",
        machineType: "Overlock",
        serialNumber: "RM-CST-1022",
        nominalEfficiency: 90,
        runtimeTodayMinutes: 405,
        maintenanceWindow: "21/03 13:00",
      },
      {
        id: "mc-05",
        code: "CST-21",
        name: "Travete Brother 21A",
        sector: "costura",
        lineId: "line-costura-02",
        machineType: "Travete",
        serialNumber: "RM-CST-1121",
        nominalEfficiency: 88,
        runtimeTodayMinutes: 356,
        maintenanceWindow: "20/03 09:00",
      },
      {
        id: "mc-06",
        code: "CST-22",
        name: "Reta eletronica Juki 22D",
        sector: "costura",
        lineId: "line-costura-02",
        machineType: "Costura reta",
        serialNumber: "RM-CST-1124",
        nominalEfficiency: 91,
        runtimeTodayMinutes: 390,
        maintenanceWindow: "24/03 16:00",
      },
      {
        id: "mc-07",
        code: "ACB-01",
        name: "Mesa revisao final A1",
        sector: "acabamento",
        lineId: "line-acab-01",
        machineType: "Revisao",
        serialNumber: "RM-ACB-7710",
        nominalEfficiency: 92,
        runtimeTodayMinutes: 344,
        maintenanceWindow: "28/03 08:00",
      },
      {
        id: "mc-08",
        code: "ACB-02",
        name: "Prensa vapor P2",
        sector: "acabamento",
        lineId: "line-acab-01",
        machineType: "Prensagem",
        serialNumber: "RM-ACB-7716",
        nominalEfficiency: 89,
        runtimeTodayMinutes: 332,
        maintenanceWindow: "27/03 11:00",
      },
      {
        id: "mc-09",
        code: "EXP-01",
        name: "Esteira embalagem E1",
        sector: "expedicao",
        lineId: "line-exp-01",
        machineType: "Embalagem",
        serialNumber: "RM-EXP-6641",
        nominalEfficiency: 87,
        runtimeTodayMinutes: 298,
        maintenanceWindow: "23/03 06:30",
      },
      {
        id: "mc-10",
        code: "EXP-02",
        name: "Leitor expedicao L2",
        sector: "expedicao",
        lineId: "line-exp-01",
        machineType: "Conferencia",
        serialNumber: "RM-EXP-6648",
        nominalEfficiency: 85,
        runtimeTodayMinutes: 284,
        maintenanceWindow: "26/03 14:30",
      },
    ],
    sectors: [
      {
        key: "corte",
        name: "Corte",
        plannedDailyOutput: 1320,
        actualDailyOutput: 1014,
        efficiency: 94,
        status: "operando",
        activeOrders: 1,
        operators: 8,
        machinesRunning: 5,
        machinesTotal: 5,
        downtimeMinutes: 5,
        defects: 7,
        alertCount: 0,
      },
      {
        key: "costura",
        name: "Costura",
        plannedDailyOutput: 2480,
        actualDailyOutput: 1988,
        efficiency: 88,
        status: "atencao",
        activeOrders: 2,
        operators: 16,
        machinesRunning: 13,
        machinesTotal: 14,
        downtimeMinutes: 14,
        defects: 18,
        alertCount: 1,
      },
      {
        key: "acabamento",
        name: "Acabamento",
        plannedDailyOutput: 1740,
        actualDailyOutput: 1418,
        efficiency: 91,
        status: "operando",
        activeOrders: 2,
        operators: 8,
        machinesRunning: 6,
        machinesTotal: 6,
        downtimeMinutes: 8,
        defects: 13,
        alertCount: 0,
      },
      {
        key: "expedicao",
        name: "Expedicao",
        plannedDailyOutput: 1500,
        actualDailyOutput: 1128,
        efficiency: 84,
        status: "atencao",
        activeOrders: 1,
        operators: 6,
        machinesRunning: 3,
        machinesTotal: 4,
        downtimeMinutes: 10,
        defects: 4,
        alertCount: 1,
      },
    ],
    orders: [
      {
        id: "ord-01",
        number: "OP-240316-01",
        productId: "prod-01",
        productName: "Camiseta basica",
        lineId: "line-costura-01",
        plannedQuantity: 3200,
        producedQuantity: 1880,
        currentSector: "costura",
        dueDate: buildDate(18, 0),
        status: "em_andamento",
        priority: "alta",
        line: "Linha 01",
        defectRate: 1.4,
        lastUpdate: anchorDate.toISOString(),
      },
      {
        id: "ord-02",
        number: "OP-240316-02",
        productId: "prod-02",
        productName: "Polo masculina",
        lineId: "line-costura-02",
        plannedQuantity: 1800,
        producedQuantity: 1395,
        currentSector: "acabamento",
        dueDate: buildDate(17, 30),
        status: "atrasada",
        priority: "alta",
        line: "Linha 03",
        defectRate: 2.1,
        lastUpdate: anchorDate.toISOString(),
      },
      {
        id: "ord-03",
        number: "OP-240316-03",
        productId: "prod-03",
        productName: "Moletom feminino",
        lineId: "line-acab-01",
        plannedQuantity: 950,
        producedQuantity: 428,
        currentSector: "costura",
        dueDate: buildDate(11, 0, 1),
        status: "em_andamento",
        priority: "media",
        line: "Linha 05",
        defectRate: 1.9,
        lastUpdate: anchorDate.toISOString(),
      },
      {
        id: "ord-04",
        number: "OP-240316-04",
        productId: "prod-04",
        productName: "Calca de uniforme",
        lineId: "line-exp-01",
        plannedQuantity: 2600,
        producedQuantity: 2335,
        currentSector: "expedicao",
        dueDate: buildDate(19, 0),
        status: "em_andamento",
        priority: "alta",
        line: "Linha 02",
        defectRate: 1.3,
        lastUpdate: anchorDate.toISOString(),
      },
      {
        id: "ord-05",
        number: "OP-240316-05",
        productId: "prod-05",
        productName: "Jaqueta leve",
        lineId: "line-corte-01",
        plannedQuantity: 720,
        producedQuantity: 126,
        currentSector: "corte",
        dueDate: buildDate(15, 0, 2),
        status: "parada",
        priority: "media",
        line: "Linha 07",
        defectRate: 2.4,
        lastUpdate: anchorDate.toISOString(),
      },
      {
        id: "ord-06",
        number: "OP-240315-17",
        productId: "prod-01",
        productName: "Camiseta basica",
        lineId: "line-exp-01",
        plannedQuantity: 1500,
        producedQuantity: 1500,
        currentSector: "expedicao",
        dueDate: buildDate(12, 30),
        status: "concluida",
        priority: "baixa",
        line: "Linha 02",
        defectRate: 0.9,
        lastUpdate: anchorDate.toISOString(),
      },
    ],
    hourlyProduction: [
      { label: "06:00", produced: 118, target: 120 },
      { label: "07:00", produced: 136, target: 145 },
      { label: "08:00", produced: 158, target: 160 },
      { label: "09:00", produced: 174, target: 175 },
      { label: "10:00", produced: 188, target: 190 },
      { label: "11:00", produced: 201, target: 205 },
      { label: "12:00", produced: 164, target: 180 },
      { label: "13:00", produced: 212, target: 210 },
      { label: "14:00", produced: 177, target: 185 },
    ],
    alerts: [
      {
        id: "alt-01",
        fingerprint: "eff-costura",
        type: "eficiencia_baixa",
        title: "Eficiencia abaixo da meta na costura",
        description:
          "Linha 03 operando com balanceamento reduzido. Ritmo 6 pontos abaixo da meta nominal.",
        severity: "medium",
        sector: "costura",
        timestamp: buildDate(14, 10),
        active: true,
        source: "simulation",
      },
      {
        id: "alt-02",
        fingerprint: "supply-op-240316-05",
        type: "suprimento",
        title: "OP-240316-05 bloqueada por falta de aviamento",
        description:
          "A jaqueta leve aguarda reposicao de ziper para liberacao da proxima etapa no corte.",
        severity: "high",
        sector: "corte",
        orderNumber: "OP-240316-05",
        timestamp: buildDate(14, 14),
        active: true,
        source: "simulation",
      },
      {
        id: "alt-03",
        fingerprint: "late-op-240316-02",
        type: "op_atrasada",
        title: "Polo masculina proxima do limite de prazo",
        description:
          "OP-240316-02 precisa atravessar acabamento ainda neste turno para nao comprometer expedicao.",
        severity: "medium",
        sector: "acabamento",
        orderNumber: "OP-240316-02",
        timestamp: buildDate(14, 16),
        active: true,
        source: "simulation",
      },
    ],
    alertHistory: [
      {
        id: "alt-h-01",
        fingerprint: "machine-exp-reader",
        type: "maquina_parada",
        title: "Parada resolvida na expedicao",
        description:
          "Leitor de conferencia retomado apos ajuste de scanner no inicio do turno.",
        severity: "info",
        sector: "expedicao",
        timestamp: buildDate(9, 5),
        active: false,
        source: "simulation",
        acknowledgedAt: buildDate(9, 18),
        acknowledgedBy: "Fernanda Costa",
        resolvedAt: buildDate(9, 22),
      },
    ],
    manualEntries: [
      {
        id: "man-01",
        timestamp: buildDate(13, 18),
        action: "iniciar_op",
        orderId: "ord-03",
        orderNumber: "OP-240316-03",
        productName: "Moletom feminino",
        sector: "costura",
        operatorId: "op-03",
        operatorName: "Miriam Dantas",
        note: "Lote liberado apos conferencia inicial.",
      },
      {
        id: "man-02",
        timestamp: buildDate(13, 42),
        action: "apontar_producao",
        orderId: "ord-01",
        orderNumber: "OP-240316-01",
        productName: "Camiseta basica",
        sector: "costura",
        operatorId: "op-06",
        operatorName: "Carlos Neri",
        quantity: 96,
        note: "Apontamento do lote intermediario da Linha 01.",
      },
      {
        id: "man-03",
        timestamp: buildDate(14, 8),
        action: "registrar_parada",
        orderId: "ord-05",
        orderNumber: "OP-240316-05",
        productName: "Jaqueta leve",
        sector: "corte",
        operatorId: "op-01",
        operatorName: "Ana Claudia",
        durationMinutes: 18,
        reason: "Aguardando reposicao de aviamento.",
      },
    ],
  };
}
